CXXFLAGS=-Wall -g -pthread -std=c++0x

all: controller

clean:
	rm -f controller

controller: crc8.c crc8.h controller.cc protocol.h
	$(CXX) crc8.c controller.cc $(OUTPUT_OPTION) $(CXXFLAGS) $(LDFLAGS)
